spring.application.name=api-gateway
server.port=8087

spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# -------- BOOKING SERVICE --------
spring.cloud.gateway.routes[1].id=booking-service
spring.cloud.gateway.routes[1].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/booking-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# -------- FLIGHT SERVICE --------
spring.cloud.gateway.routes[2].id=flight-service
spring.cloud.gateway.routes[2].uri=lb://FLIGHT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/flight-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Eureka (Docker-safe)
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# IMPORTANT: use service name, not localhost
auth.service.base-url=http://auth-service:8085

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

logging.level.org.springframework.cloud.gateway=INFO
# ===== SECURITY & GATEWAY DEBUG =====
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.apigateway=DEBUG
logging.level.reactor.netty.http.server=DEBUG

jwt.secret=3e1c0f59a7d58491d24e0e97fa30f909fe12a8cf4a4e842dcb197eba1fbdc25e

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=Authorization,Content-Type
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
