spring.application.name=api-gateway
server.port=8087

spring.main.web-application-type=reactive

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.strip-prefix=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka (Docker-safe)
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# IMPORTANT: use service name, not localhost
auth.service.base-url=http://auth-service:8085

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

logging.level.org.springframework.cloud.gateway=INFO

jwt.secret=3e1c0f59a7d58491d24e0e97fa30f909fe12a8cf4a4e842dcb197eba1fbdc25e
