spring.application.name=auth-service
server.port=8085

# ==========================
# DATABASE (LOCAL)
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/authdb
spring.datasource.username=root
spring.datasource.password=Ananya2004!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# EUREKA (LOCAL)
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=booking.exchange
app.rabbitmq.routing.password.reset=auth.password.reset

# ==========================
# JWT
# ==========================
jwt.secret=3e1c0f59a7d58491d24e0e97fa30f909fe12a8cf4a4e842dcb197eba1fbdc25e
jwt.expirationSeconds=3600

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG
logging.level.com.authservice=DEBUG
